### ISSUE TITLE
Get error on step npm run sample-test

### ISSUE THREAD

**Issue by KaushikChavda** [browserstack/node-js-playwright-browserstack#2]
Hello Support,
 
I’m following the steps and get error on Step 4:
https://www.browserstack.com/docs/automate/playwright/getting-started/nodejs#MacOS_or_Linux 
 

1) [playwright-webkit@latest:OSX Ventura] › sample_test.js:4:1 › BstackDemo Add to cart ==========
 
    browserType.launch: Browser has been closed
 
        at Object.playwrightFixtures.browser.scope [as fn] ([/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/index.js:180:51](mailto:/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/index.js:180:51))
        at [/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/fixtures.js:95:81](mailto:/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/fixtures.js:95:81)
 
  2) [chrome@latest:Windows 11] › sample_test.js:4:1 › BstackDemo Add to cart ======================
 
    browserType.launch: Browser has been closed
 
        at Object.playwrightFixtures.browser.scope [as fn] ([/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/index.js:180:51](mailto:/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/index.js:180:51))
        at [/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/fixtures.js:95:81](mailto:/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/fixtures.js:95:81)
 
  3) [playwright-firefox:Windows 11] › sample_test.js:4:1 › BstackDemo Add to cart =================
 
    browserType.launch: Browser has been closed
 
        at Object.playwrightFixtures.browser.scope [as fn] ([/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/index.js:180:51](mailto:/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/index.js:180:51))
        at [/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/fixtures.js:95:81](mailto:/Users/kaushikchavda/Projects/node-js-playwright-browserstack/node_modules/@playwright/test/lib/fixtures.js:95:81)
 
 
  3 failed
    [chrome@latest:Windows 11] › sample_test.js:4:1 › BstackDemo Add to cart =======================
    [playwright-webkit@latest:OSX Ventura] › sample_test.js:4:1 › BstackDemo Add to cart ===========
    [playwright-firefox:Windows 11] › sample_test.js:4:1 › BstackDemo Add to cart ==================

**Comment by spencersablan** [comment]
Ahhh I think I got it. Two things:
1. Make sure you've downloaded Browserstack local
2. In `exports.BS_LOCAL_ARGS`, be sure to put your access key.

**Comment by spencersablan** [comment]
> HI @spencersablan please i get kind of a similar error but i cant find where to add the exports.bs_local_Args based on the examples in the doc. please where do i add this?

Check out this doc! https://www.browserstack.com/docs/automate/playwright/playwright-capabilities

You'll find it there 😄
